### ISSUE TITLE
My Own Page

### ISSUE THREAD

**Issue by Faranch** [JimTheMan/t2#13]
I think we should have a separate page where people can only see their videos with possibly a notepad too. For simplicity's sake, it could simply be a room that only that specific user can access. I feel that people are always going to want to watch themselves, and want to have a separate page that only they can see inside. The notepad could also be a cool feature, but it might be too "old school" and hipsterish

**Comment by JimTheMan** [comment]
Yeah,  we've been talking about this for a while, but idk if this is the right time to implement it. We should  prove that the core functionality works first.

Also, it would be nice to have a visual mock-up of what this page should look like.

**Comment by JimTheMan** [comment]
Just added a "my profile" page. You can get to it from the top-right corner of the cypher room header. I'm thinking about putting that header across all the pages actually.

**Comment by JimTheMan** [comment]
I closing this rambling-ass issue. If you think the current "my-profile" page should have the user's videos please describe it in a new issue.
