### ISSUE TITLE
Upload Error Feedback text

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#14]
In addition to a percentage uploaded indicator I think it would be nice to display a message if the upload fails / file is too big / etc.

**Comment by Faranch** [comment]
I think we should have this on a separate page where its both a place to record and watch one's old videos. Could we have a small notification in one of the corners?

**Comment by shivpatel779** [comment]
@JimTheMan 

yes we can show error message for files is big...

**Comment by shivpatel779** [comment]
@JimTheMan @Faranch 

But right now layout look very ugly manner so, please leave some suggestion for look and feel so that we can easily identify functionalities as well...

**Comment by JimTheMan** [comment]
What feedback are we talking about here. Let's close this and make a more specific issue.
