### ISSUE TITLE
New Feature: X button to remove videos

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#2]
Currently, there is no way to remove videos. The feature I am proposing will allow users to delete videos, _but only their own videos._

Of course, we don't want trolls jumping into a room and just deleting all the videos. So my idea was that a user can only delete his or her own videos, not those of the other users.

I think a good way to implement this would button an x button in the sidebar next to the button for the given video. Here's a screenshot of what I'm trying to say:

![cypherapp_](https://cloud.githubusercontent.com/assets/5354163/19701653/44616084-9aca-11e6-90a4-468e77b63db4.gif)

In the sidebar on the right we currently have a button for each video. This button can be clicked to have the video player jump to the beginning of that particular video. I'm thinking an x button to the right of the video button would be a nice UX for deleting a video. Of course, this x button would only show when the _uploader_ value for that video is the same as the uid of the current user logged in. 

Thoughts? Let me know what you guys think about this feature (@Faranch) .

**Comment by Faranch** [comment]
I explained this in another Issue, but maybe we could have a My Own Page that is like a room, but where users can delete their videos. Users shouldnt be openly given the choice to delete these videos because they are short as hell already, but we can use that X icon you proposed for the My Own Page room.

**Comment by Faranch** [comment]
Or we can have an Edit button to the side that lets u delete or reorder videos right there. Your thoughts?

**Comment by JimTheMan** [comment]
Hmm. Idk. I was thinking put the delete button right in the room. If they delete it in the room then yeah, I would think it deletes it from the "my profile" page as well. If they delete from the my profile page though, does it get deleted in the room too?

**Comment by JimTheMan** [comment]
I added a trash button that activates "delete mode". Only in delete mode to the x buttons appear, and even in delete mode the x buttons only appear for videos that the current user has uploaded.
