### ISSUE TITLE
Removing the chatbox

### ISSUE THREAD

**Issue by Faranch** [JimTheMan/t2#22]
Editing, hold on

**Comment by Faranch** [comment]
![20161122_231513](https://cloud.githubusercontent.com/assets/22310425/20551038/b633eaec-b109-11e6-8c42-448be8a65f64.jpg)

**Comment by Faranch** [comment]
![20161122_182640](https://cloud.githubusercontent.com/assets/22310425/20551048/dcb98f78-b109-11e6-8e5d-2f9fc6b53461.jpg)

**Comment by Faranch** [comment]
![20161122_231806](https://cloud.githubusercontent.com/assets/22310425/20551070/18c072e8-b10a-11e6-963c-bbccfe575f73.jpg)

**Comment by JimTheMan** [comment]
Chat has been removed in latest "New layout" merge
