### ISSUE TITLE
Position bottom buttons to be in correct spot all mobile screens

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#28]
Currently, the big green buttons on the bottom of the screen are just floating to the left with some margin spacer.

![screen shot 2016-11-24 at 12 46 17 am](https://cloud.githubusercontent.com/assets/5354163/20587995/a30f1762-b1df-11e6-8708-7b2d5692e454.png)

The buttons should be centered nicely in this section, even spaced out.

**Comment by shivpatel779** [comment]
@JimTheMan 
Fixed
