### ISSUE TITLE
Lock Text Under Video to Bottom of Video Container

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#29]
Currently the information under the video is floating right under the video for any video height.

![cypherapp](https://cloud.githubusercontent.com/assets/5354163/20588116/b32c95f6-b1e0-11e6-84b5-c012b6365bd7.png)

Really, the text displayed here should always be "locked" to the bottom of this video container (as shown by the pink rectangle).

**Comment by shivpatel779** [comment]
@JimTheMan 
Fixed
