### ISSUE TITLE
Give Big Green "Jump In" Button the Functionality Currently on the Yellow "Upload" Button

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#34]
![cypherapp](https://cloud.githubusercontent.com/assets/5354163/20612533/fbebb4e0-b288-11e6-948d-8738083e1a88.png)

Currently, the yellow upload button does work to upload videos to firebase. What we really want though is for the "Jump In" button to allow the user to upload a video so that we can remove the yellow button.

This is a little tricky because the yellow button is actually a <video> tag styled with an image, and the green button is just a <button> tag.

**Comment by shivpatel779** [comment]
@JimTheMan

**Comment by shivpatel779** [comment]
@JimTheMan 

Done
