### ISSUE TITLE
Add a "Take Back Props" button

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#35]
Currently, when a user gives props to a video by clicking the big green "Give Props" button then another yellow button appears that allows the user to "Take Back Props":

![cypherapp](https://cloud.githubusercontent.com/assets/5354163/20612596/a263c704-b289-11e6-8586-8d4f817d8d53.png)

Instead of this yellow button there should be another button the same size as the current "Give Props" button, but the new one should be labeled "Take Back Props" and should be a slightly darker green color. Only one button or the other shows depending on whether or not the user has given props already to the current playing video.

**Comment by shivpatel779** [comment]
@JimTheMan 

Done
