### ISSUE TITLE
Room Buttons On Main Page Should Go to Rooms With "Cypher-Room-V2"

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#38]
Currently the buttons on the front page go to the v1 version using the angular component "cypher-room". These should instead be using cypher-room-v2 component (formerly known as test-layout-page). 

Also, would be nice to have these room buttons be a little prettier. Ideas @faranch?

**Comment by shivpatel779** [comment]
@JimTheMan Done
