### ISSUE TITLE
Chat TextArea should scroll down to show latest message

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#4]
When new text gets put in the chat textarea, the textarea should scroll down automatically (scrollv?) instead of the user having to manually scroll the chat (derp!!).

**Comment by Faranch** [comment]
Or it can be an arrow that lets you know "Hey, there are # new chat messages down below" (nh). I feel that apps that do the work for you of scrolling automatically, unless a person just logged in or went to the page, stifle further usage by users: people might prefer the notice and option to scroll down

**Comment by JimTheMan** [comment]
I made it scroll down now. If you want some kind of message saying "hey, new messages" just open another issue for that.
