### ISSUE TITLE
Loading Text Should Be Centered

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#44]
I just tried the latest version, and the loading text is not centered on my phone. Please check the CSS for the positioning and use chrome dev tools responsive device mode.

![screenshot_2016-11-28-09-44-17](https://cloud.githubusercontent.com/assets/5354163/20672801/7c2170a4-b550-11e6-9b5c-d70942692574.png)

**Comment by shivpatel779** [comment]
@JimTheMan  Done
