### ISSUE TITLE
Change Title To Cypher City

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#45]
We bought the cypher.city donation name so we should keep going with that. The only thing is should the text in the header bar say "Cypher City" or "Cypher.City"?

What do you guys think? @faranch @taif95

**Comment by shivpatel779** [comment]
@JimTheMan  Done

**Comment by taif95** [comment]
What does that mean exactly, cypher city donation ? The header shouldn't have (.) in it in my opinion. It should just be "Cypher City"
