### ISSUE TITLE
Route Transition Fade-In/ Fade-Out Animation On Cypher-room-v2 page

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#48]
Here, we would like the screen to fade in when the user navigates to a room with "cypher-room-v2" component and fade out when navigating away from in. By "fade" I mean the css property opacity transitioning from 0 to 1 or 1 to 0.

Let me know if you have another questions on this @shivpatel779 . :)

**Comment by shivpatel779** [comment]
@JimTheMan got it..I will update you once its done.

**Comment by shivpatel779** [comment]
@JimTheMan  completed
