### ISSUE TITLE
Trash btn

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#49]
Page: cypher-room-v2

Expected behavior: When trash mode is activate, the whole trash button should be red.

Current behavior: When trash mode is activate, the trash button is still mostly grey and only the icon has a red background.

![cypher_city](https://cloud.githubusercontent.com/assets/5354163/20867795/54b0a3e0-ba1a-11e6-970d-31580eef3d79.png)

When the trash button is not active, it should be grey (like it is currently):

![cypher_city](https://cloud.githubusercontent.com/assets/5354163/20867803/6c77503c-ba1a-11e6-9db8-60495a67095f.png)

**Comment by shivpatel779** [comment]
@JimTheMan  Done

**Comment by JimTheMan** [comment]
trash button is no longer functional

**Comment by shivpatel779** [comment]
@JimTheMan The videos which you will upload will only be deleted.

**Comment by shivpatel779** [comment]
@JimTheMan  I have fixed this. Please test it now and let me know.
