### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#5]
Need to improve colors. Thoughts Faran?

**Comment by Faranch** [comment]
How about we try a baby blue, rosey pink, and black theme? 

Or instead, a black and gold theme. The video boxes can be gold with white text. It should be a shade of yellowish gold such that the video boxes on the side do not look annoying to the eyes nor tacky. I like the black background and white text, but we can throw gold in there to give it a regal look. Maybe use red for the other things like borders and the title of the app in the Room

We also talked about purple text on a white background but it may be hard to read imo

**Comment by JimTheMan** [comment]
@shivpatel779 Are you working on those one?

**Comment by shivpatel779** [comment]
Yes

**Comment by shivpatel779** [comment]
@JimTheMan @Faranch 

Hey, its does not make any sense with mention color names and all, do you have any idea how your page want look, please share template or PSD file so that we can build with new design and all

**Comment by JimTheMan** [comment]
Guys, please check the latest "blue colors" and open a new issue if needed.
