### ISSUE TITLE
Pretty Styling For Rooms List Modals

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#54]
I just implemented these modals that use the ng2-bs3-modal libary: 
https://github.com/dougludlow/ng2-bs3-modal

These are used on the rooms-list page when the user clicks "Join Private Cypher" or "Create Private Cypher". Currently, they just use plain, boring styles:

![cypher_city](https://cloud.githubusercontent.com/assets/5354163/20873529/48d07404-ba76-11e6-948c-fcbcdca7291f.png)
![cypher_city](https://cloud.githubusercontent.com/assets/5354163/20873534/5518219e-ba76-11e6-86a8-85f6157b64e4.png)

The buttons in the footer of the modal are fine. In particular, I would like: 
- font size increased a bit 
- changed to the fonts currently used (Raleway for header text, Helvetica Neue for body text), 
- make the inputs prettier, rounded corners, Helvetica Neue text, slight padding / shadows
- center text input

**Comment by shivpatel779** [comment]
@JimTheMan  Done

**Comment by JimTheMan** [comment]
modals still look the same

**Comment by shivpatel779** [comment]
@JimTheMan Please test it now, still if you want any changes please let me know.
