### ISSUE TITLE
Implement Functionality For "Step Backward" and "Step Forward" Buttons

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#56]
These buttons control the video player. The "step backward" button should jump to the previous video, and the "step forward" button should jump to the next video.

![cypher_city_and_cypher-room-v2_html_-_t2_-____git-projects_t2_](https://cloud.githubusercontent.com/assets/5354163/20873931/d28abe94-ba7a-11e6-95e6-8f7af222e397.png)

**Comment by shivpatel779** [comment]
@JimTheMan I have coded for this but its not working peroperly, so i will fix it tomorrow. For now it works fine once you reload the page of video player.

**Comment by shivpatel779** [comment]
@JimTheMan  Done

**Comment by JimTheMan** [comment]
Still not working properly. @shivpatel779 please look into this

**Comment by shivpatel779** [comment]
@JimTheMan  Fixed this issue. Please check it now
