### ISSUE TITLE
Implement Play / Pause Buttons

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#57]
These buttons should control the video player. When a video is playing the play button should be hidden and only the pause button should be visible. Clicking the pause button should pause the video. Then the pause button disappears and the play button becomes visible. Clicking the play button then resumes the video playback.

![cypher_city_and_cypher-room-v2_html_-_t2_-____git-projects_t2_](https://cloud.githubusercontent.com/assets/5354163/20873956/1f5af194-ba7b-11e6-9d35-845ecee69ebc.png)

**Comment by shivpatel779** [comment]
@JimTheMan I have coded for this but its not working peroperly, so i will fix it tomorrow. For now it works fine once you reload the page of video player.

**Comment by shivpatel779** [comment]
@JimTheMan Done

**Comment by JimTheMan** [comment]
@shivpatel779 , please don't use JQuery selectors. I had to go in and fix this myself. Please look at current code now.
