### ISSUE TITLE
Implement FullScreen Video Button

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#58]
Clicking this button should expand the video player to take up the whole screen.

![cypher_city_and_cypher-room-v2_html_-_t2_-____git-projects_t2_](https://cloud.githubusercontent.com/assets/5354163/20873973/41e01f46-ba7b-11e6-98aa-a779e01ea303.png)

**Comment by shivpatel779** [comment]
@JimTheMan  I have coded for this but its not working peroperly, so i will fix it tomorrow. For now it works fine once you reload the page of video player.

**Comment by shivpatel779** [comment]
@JimTheMan Done

**Comment by JimTheMan** [comment]
video should take up full screen. Current, video doesn't scale when entering fullscreen mode.

**Comment by shivpatel779** [comment]
@JimTheMan  Done
