### ISSUE TITLE
Fix Layout For Tiny Chode Screens

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#62]
Looks bad on my phone:

![screenshot_2016-12-05-14-02-48](https://cloud.githubusercontent.com/assets/5354163/20898295/c6ecc9dc-baf3-11e6-98ae-c3c6f4e743ec.png)

**Comment by shivpatel779** [comment]
@JimTheMan  Done

**Comment by JimTheMan** [comment]
![cypher_city_and_fix_layout_for_tiny_chode_screens_ _issue__62_ _jimtheman_t2_and_jenkinstest_ _-bash_ _141x32](https://cloud.githubusercontent.com/assets/5354163/21062984/5c4e815c-be21-11e6-867a-d387c5a2e5c5.png)

**Comment by shivpatel779** [comment]
@JimTheMan  task Completed
