### ISSUE TITLE
Buttons Cut Off On Screens With Short Height

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#70]
Currently, short height screens look like this:

![cypher_city_and_cypher-room-v2_component_ts_-_t2_-____git-projects_t2__and_cypherapp_ _angular-cli_term_program_apple_terminal_term_xterm-256color_ _122x23_and_jims-ngrx-eg_ _-bash_ _128x24](https://cloud.githubusercontent.com/assets/5354163/21011816/0ce54016-bd21-11e6-83d0-7e0afc79e3c5.png)

What should happen is the buttons stay near the bottom of the screen while the main rooms list shrinks.

**Comment by shivpatel779** [comment]
@JimTheMan Done

**Comment by JimTheMan** [comment]
Buttons are still not positioned properly (on any sized device really).

1. text should always be centered inside button bounds

2. button should always be centered vertically in dark blue section

**Comment by shivpatel779** [comment]
![1](https://cloud.githubusercontent.com/assets/20398940/21090256/70993356-c064-11e6-9b5f-6d35296072e4.png)
@JimTheMan I have already fixed these issue

**Comment by shivpatel779** [comment]
@JimTheMan  Hey Sorry I checked with different browser..this is having issue, let me fix it :)

**Comment by shivpatel779** [comment]
@JimTheMan I have completed this task.
