### ISSUE TITLE
Green Buttons Not Right

### ISSUE THREAD

**Issue by JimTheMan** [JimTheMan/t2#71]
Green Button are stacked on top of each other when they should be one next to the other:

![cypher_city_and_add_editable__room_description__ _issue__39_ _jimtheman_t2_and_cypher-room-v2_component_ts_-_t2_-____git-projects_t2__and_cypherapp_ _angular-cli_term_program_apple_terminal_term_xterm-256color_ _122x23_and_jims-ngrx-eg_ _-b](https://cloud.githubusercontent.com/assets/5354163/21011897/710d6730-bd21-11e6-846a-af6b6188f35d.png)

**Comment by shivpatel779** [comment]
@JimTheMan  Done
