### ISSUE TITLE
Loading Icons and Text

### ISSUE THREAD

**Issue by Faranch** [JimTheMan/t2#8]
Currently, there is "Loading..." text when going to the Front Page, the Room Page, and when refreshing both pages. In lieu of these default pages, I propose we either use a gif or html text like three dots a la Christmas lights, perhaps with our own icon. It should be something aesthetically pleasing and unique instead of just a default screen. 

Also, there are no icons for both the Uploading Percentage and loading of the videos on the side as well as the main video playing. We could use something like a microphone with sparks coming out or something to that effect. Both the page loading and videos loading icons could be the same, or not. I think they should not.

These icons should illustrate to the users that this shit is legit as shit, and be good enough. Awh yea

**Comment by Faranch** [comment]
Also, we should explore adding a Confirm Upload a Video button that also changes into a percentage meter showing how long a video will take to upload. The videos are short but it would present a little flair while showing people this is legit and that the page is working, and not frozen or anything.

**Comment by JimTheMan** [comment]
The original issue was about the initial "splash screen" loading which we have now (black screen with white text "Loading Cyphers" and a spinning wheel. Then you start talking about the upload button loading which we have "Mixing XX%" ( with another spinning font-awesome circle. Gotta love those spinning waiting circles). So yeah, I'm going to close this issue now. ok bye.
